### PR TITLE
Success with Windows only

### PR DESCRIPTION
**Pull request by tbrowder**
I would split the test.yml files into three seperate OS test files. By commenting out Linux and MacOS, I got two good Windows runs with my Windows changes.

### CODE REVIEW

**Comment by dwarring** [comment]
Totally agree with removing mingw install. It's left over from before the prebuilt DLL was added and shouldn't be there.

Windows tests failed, due to but I'm having similar issues with testing my other modules on Windows.

I think the minimum Rakudo version 2021.08 should either be bumped to a more recent version (say 2022.07), or just commented out. I've need to do the same recently with other modules such as PDF and PDF::Content.

**Comment by dwarring** [comment]
Can test.yml now be deleted? Seems it's now redundant with the separate windows, macos and linux tests.

**Comment by dwarring** [comment]
Actually it only seems to have run test.yml, not linux.yml etc.

**Comment by tbrowder** [comment]
Okay, David, now the three OS tests are cleanly separated, and it looks to me like all three passed.

**Comment by dwarring** [comment]
Thank Tom.

**Comment by dwarring** [comment]
Released with Base64::Native 0.0.9

**Comment by tbrowder** [comment]
You are very welcome, David, and I so appreciate your PDF suite!

**Pull request merged**
